[package]
name = "aspc"
version = "0.1.0"
authors = ["mhornick"]
edition = "2018"
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = { version = "*", features = ["trace"]}
pest = "*"
pest_derive = "*"
anyhow = "*"